name: Release

on:
  push:
    tags:
      - '*'

permissions: {}

concurrency:
  group: global
  cancel-in-progress: false

jobs:
  latest:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for gh release

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: '7.4'
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Set version
        run: sed -i "s/setVersion('latest-develop')/setVersion('$GITHUB_REF_NAME')/g" bin/roger-q.php

      - name: Generate phar
        run: make dist

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" ./dist/roger-q.phar \
            --title "$GITHUB_REF_NAME" \
            --notes "Stable release."
