name: GitHub Actions Security Analysis with zizmor 🌈

# to upgrade repository actions with a new hash, either manually look up the hash in their releases,
# or run zizmor --fix with the --gh-token parameter to have it fetch those hashes from GitHub.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
